---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: firewall
    image: ${MOLECULE_DOCKER_IMG_DISTRO}
    pre_build_image: true
    privileged: true
    command: sleep infinity
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: client
    image: ${MOLECULE_DOCKER_IMG_DISTRO}
    pre_build_image: true 
    privileged: true
    command: sleep infinity
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml

verifier:
  name: ansible
